defaults:
  - base_flux2_klein
  - _self_
cfg:
  input_uri: ???
  manifest_uri: ???
  output_uri: ???
  root_uri: ???
  buckets: ???
  batch_size: ???
  pretrained_model_name_or_path: ???
  condition: ???
  ckpt_path: ???